#!/usr/bin/env bash
set -euo pipefail

# Generate BDD verification reports (HTML + markdown summary).
# Run from the src/ directory: ./generate-bdd-report.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERIFICATION_DIR="$REPO_ROOT/docs/business/verification"
RESULTS_DIR="$SCRIPT_DIR/test-results"
TRX_FILE="$RESULTS_DIR/bdd-results.trx"
HTML_FILE="$RESULTS_DIR/bdd-results.html"
OUTPUT_HTML="$VERIFICATION_DIR/bdd-results.html"
OUTPUT_MD="$VERIFICATION_DIR/bdd-status.md"

mkdir -p "$VERIFICATION_DIR"
mkdir -p "$RESULTS_DIR"

echo "Running BDD tests..."
dotnet test "$SCRIPT_DIR/tests/CompileAndSip.Bdd.Tests" \
  --logger "trx;LogFileName=bdd-results.trx" \
  --logger "html;LogFileName=bdd-results.html" \
  --results-directory "$RESULTS_DIR" \
  --verbosity quiet

if [[ ! -f "$TRX_FILE" ]]; then
  echo "ERROR: TRX file not found at $TRX_FILE"
  exit 1
fi

echo "Copying HTML report..."
cp "$HTML_FILE" "$OUTPUT_HTML"

echo "Generating markdown summary..."

# Parse TRX using grep/awk (no Python xml module needed in minimal installs)

# Extract summary counters
TOTAL=$(grep -oP 'total="\K[0-9]+' "$TRX_FILE" | tail -1)
PASSED=$(grep -oP ' passed="\K[0-9]+' "$TRX_FILE" | tail -1)
FAILED=$(grep -oP ' failed="\K[0-9]+' "$TRX_FILE" | tail -1)
SKIPPED=$((TOTAL - PASSED - FAILED))

# Extract timestamp from finish attribute
FINISH_RAW=$(grep -oP 'finish="\K[^"]+' "$TRX_FILE")
TIMESTAMP=$(date -u -d "${FINISH_RAW}" '+%Y-%m-%d %H:%M UTC' 2>/dev/null || date -u '+%Y-%m-%d %H:%M UTC')

# Extract per-class test counts using className from TestDefinitions
# Build a temp file mapping testId -> className suffix
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

# Extract testId->className mapping from UnitTest/TestMethod elements
grep -oP 'UnitTest[^>]*id="\K[^"]+' "$TRX_FILE" > "$TEMP_DIR/test_ids.txt"
grep -oP 'className="[^"]*\.(\w+Feature)"' "$TRX_FILE" | grep -oP '\w+Feature' > "$TEMP_DIR/class_names.txt"
paste "$TEMP_DIR/test_ids.txt" "$TEMP_DIR/class_names.txt" > "$TEMP_DIR/id_class_map.txt"

# Extract testId->outcome from UnitTestResult elements
grep -oP 'UnitTestResult[^>]*testId="\K[^"]+' "$TRX_FILE" > "$TEMP_DIR/result_ids.txt"
grep -oP 'UnitTestResult[^>]*outcome="\K[^"]+' "$TRX_FILE" > "$TEMP_DIR/outcomes.txt"
paste "$TEMP_DIR/result_ids.txt" "$TEMP_DIR/outcomes.txt" > "$TEMP_DIR/id_outcome_map.txt"

# Join on testId and count per class
declare -A CLASS_PASSED CLASS_FAILED CLASS_TOTAL
while IFS=$'\t' read -r test_id class_name; do
  outcome=$(grep "^${test_id}" "$TEMP_DIR/id_outcome_map.txt" | cut -f2)
  CLASS_TOTAL[$class_name]=$(( ${CLASS_TOTAL[$class_name]:-0} + 1 ))
  if [[ "$outcome" == "Passed" ]]; then
    CLASS_PASSED[$class_name]=$(( ${CLASS_PASSED[$class_name]:-0} + 1 ))
  elif [[ "$outcome" == "Failed" ]]; then
    CLASS_FAILED[$class_name]=$(( ${CLASS_FAILED[$class_name]:-0} + 1 ))
  fi
done < "$TEMP_DIR/id_class_map.txt"

# Scenario mapping: class suffix -> SCN ID, name, feature file
declare -A SCN_ID SCN_NAME SCN_FILE
SCN_ID[BrowseMenuAndSelectDrinkFeature]="SCN-001"
SCN_NAME[BrowseMenuAndSelectDrinkFeature]="Browse Menu and Select Drink"
SCN_FILE[BrowseMenuAndSelectDrinkFeature]="SCN-001-browse-menu-select-drink.feature"

SCN_ID[CustomiseDrinkFeature]="SCN-002"
SCN_NAME[CustomiseDrinkFeature]="Customise Drink"
SCN_FILE[CustomiseDrinkFeature]="SCN-002-customise-drink.feature"

SCN_ID[PaymentSucceedsFeature]="SCN-003"
SCN_NAME[PaymentSucceedsFeature]="Payment Succeeds"
SCN_FILE[PaymentSucceedsFeature]="SCN-003-payment-succeeds.feature"

SCN_ID[PaymentFailsFeature]="SCN-004"
SCN_NAME[PaymentFailsFeature]="Payment Fails"
SCN_FILE[PaymentFailsFeature]="SCN-004-payment-fails.feature"

SCN_ID[KitchenMarksOrderCompleteFeature]="SCN-005"
SCN_NAME[KitchenMarksOrderCompleteFeature]="Kitchen Marks Order Complete"
SCN_FILE[KitchenMarksOrderCompleteFeature]="SCN-005-kitchen-marks-order-complete.feature"

# Generate markdown
{
  echo "# BDD Verification Status"
  echo ""
  echo "<!-- BEGIN GENERATED: bdd-status -->"
  echo ""
  echo "> Generated by \`src/generate-bdd-report.sh\` — do not edit manually."
  echo "> Last run: $TIMESTAMP"
  echo ""
  echo "## Summary"
  echo ""
  echo "| Result | Count |"
  echo "|--------|-------|"
  echo "| Passed | $PASSED |"
  echo "| Failed | $FAILED |"
  echo "| Skipped | $SKIPPED |"
  echo "| **Total** | **$TOTAL** |"
  echo ""
  echo "## Scenario Results"
  echo ""
  echo "| Scenario | Feature File | Tests | Status |"
  echo "|----------|-------------|-------|--------|"

  for class in BrowseMenuAndSelectDrinkFeature CustomiseDrinkFeature PaymentSucceedsFeature PaymentFailsFeature KitchenMarksOrderCompleteFeature; do
    p=${CLASS_PASSED[$class]:-0}
    f=${CLASS_FAILED[$class]:-0}
    t=${CLASS_TOTAL[$class]:-0}
    if [[ $f -gt 0 ]]; then
      status="❌ Fail"
      detail="$p passed, $f failed"
    elif [[ $t -eq 0 ]]; then
      status="⚠️ No tests"
      detail="0 tests"
    else
      status="✅ Pass"
      detail="$p passed"
    fi
    echo "| ${SCN_ID[$class]} — ${SCN_NAME[$class]} | \`${SCN_FILE[$class]}\` | $detail | $status |"
  done

  echo ""
  echo "## Detailed Report"
  echo ""
  echo "For a richer interactive view, open [bdd-results.html](bdd-results.html) in a browser."
  echo ""
  echo "<!-- END GENERATED -->"
} > "$OUTPUT_MD"

echo "Markdown summary written to $OUTPUT_MD"

echo "Done. Reports generated:"
echo "  HTML:     $OUTPUT_HTML"
echo "  Markdown: $OUTPUT_MD"
